@startuml

title "ELMO - Sequence Diagram"

actor User

User -> ELMO : Request traces for program
activate ELMO

ELMO -> "QEMU" : Run program in GDB
activate QEMU

"QEMU" -> "GDB Server" : Debug program
activate "GDB Server"

ELMO -> "GDB Client" : Debug program
activate "GDB Client"

ELMO -> "GDB Client" : Request dissasmbly
"GDB Client" -> "GDB Server" : Request dissasmbly
"GDB Client" <-- "GDB Server" : Pass dissasmbly
"ELMO" <-- "GDB Client" : Pass dissasmbly

loop
    ELMO -> "GDB Client" : Request Registers
    "GDB Client" -> "GDB Server" : Request Registers
    "GDB Client" <-- "GDB Server" : Pass Registers
    ELMO <-- "GDB Client" : Pass Registers
    ELMO -> "GDB Client" : Run next assembly instruction
    "GDB Client" -> "GDB Server" : Run next assembly instruction
end

"GDB Client" <-- "GDB Server" : Program finished
deactivate "GDB Server"
deactivate QEMU
ELMO <-- "GDB Client" : Program finished
deactivate "GDB Client"


database "Coefficients" as Coefficients
database "Traces" as Traces

ELMO -> Coefficients : Load coefficients
activate Coefficients
ELMO <-- Coefficients : Load coefficients
deactivate Coefficients

ELMO -> ELMO : Generate traces

opt
    ELMO -> Traces : Save traces
    activate Traces
    ELMO <-- Traces : Save traces
    deactivate Traces
else
    User <-- ELMO : Pass coefficients
end

deactivate ELMO

@enduml
