@startuml

title "ELMO - Sequence Diagram"

actor User

User -> ELMO : Request traces for program
activate ELMO

par
    ELMO -> "Assembly Re-orderer" : Re-order assembly
    note right: To better emulate hardware optimisations
    activate "Assembly Re-orderer"
    ELMO <-- "Assembly Re-orderer" : Pass Re-ordered assembly
    deactivate "Assembly Re-orderer"

    ELMO -> "Unicorn-Engine" : Run program in Unicorn Engine
    activate "Unicorn-Engine"
    ELMO <-- "Unicorn-Engine" : Pass execution information
    deactivate "Unicorn-Engine"
else
    database "Coefficients" as Coefficients
    database "Traces" as Traces

    ELMO -> Coefficients : Load coefficients
    activate Coefficients
    ELMO <-- Coefficients : Load coefficients
    deactivate Coefficients
end

ELMO -> ELMO : Generate traces

opt
    ELMO -> Traces : Save traces
    activate Traces
    ELMO <-- Traces : Save traces
    deactivate Traces
else
    User <-- ELMO : Pass coefficients
end

deactivate ELMO

@enduml
