@startuml

title GILES - Use Case Diagram


rectangle ELMO {
    (Generate traces for code) as Generate
    (Load coefficients from file) as Load
    (Save generated traces to file) as Save
    rectangle Unicorn-Engine {
        (Emulate running of code) as Emulate
    }
}

:User:

User -> Generate : Request traces
Emulate ..> Generate : <<include>>
Load ..> Generate : <<include>>
Save ..> Generate : <<extends>>

@enduml
