/*
    This file is part of ELMO-2.

    ELMO-2 is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ELMO-2 is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with ELMO-2.  If not, see <http://www.gnu.org/licenses/>.
*/

/*!
    @file Model_Factory.hpp
    @brief Contains the Model_Factory class; a factory class for initialisation
    of models.
    @author Scott Egerton
    @date 2017-2018
    @copyright GNU Affero General Public License Version 3+
*/

#ifndef MODEL_FACTORY_HPP
#define MODEL_FACTORY_HPP

#include <memory>        // for unique_ptr
#include <stdexcept>     // for inva...
#include <string>        // for oper...
#include <unordered_map> // for unordered_map

#include "Model.hpp"

namespace ELMO2
{
namespace Internal
{

//! @class Model_Factory
//! @brief This is a static factory class that assists in the construction of
//! models. By providing abstraction for the caller of the Model_Factory, it
//! hides the type of the model from the caller and allows the caller to make
//! use of the model through the Model base class interface regardless of the
//! derived type.
//! @note This class contains functionality that is generated by CMake. This
//! simplifies the process of adding and removing models and allows models to
//! be selectively compiled as a way to completely remove those as options.
//! @see https://en.wikipedia.org/wiki/Factory_method_pattern
class Model_Factory
{

public:
    //! A function pointer used to point to the function that calls the
    //! constructor for objects in the factory.
    using Create_Function =
        std::unique_ptr<Model> (*)(const ELMO2::Internal::Execution&,
                                   const ELMO2::Internal::Coefficients&);

    //! @brief This function assists with the initialisation of the models.
    //! This will be passed the parameters to be passed on to the model
    //! constructor. It will selectively construct a model based on the
    //! first parameter, p_model_type and return a pointer to it.
    //! @param p_model_type The type of the model to be constructed as a
    //! string.
    //! @param p_execution The Execution as received from the emulator.
    //! @param p_coefficients The Coefficients as loaded from the
    //! coefficients file.
    //! @returns A unique pointer to the constructed model. The type of this
    //! is to the base Model class allowing the caller to ignore the actual
    //! type of the model and make use of the Model class interface.
    static std::unique_ptr<ELMO2::Internal::Model>
    Construct(const std::string& p_model_type,
              const ELMO2::Internal::Execution& p_execution,
              const ELMO2::Internal::Coefficients& p_coefficients);

    //! @brief This registers classes in the list available to the factory,
    //! allowing the factory to create an instance of anything within the list.
    //! This is needed to that classes can self register meaning that the list
    //! of classes available does not need to be hard coded.
    //! @see https://www.bfilipek.com/2018/02/factory-selfregister.html
    //! @param p_type A string representing the type of the class being
    //! registered. This is used to identify classes.
    //! @param p_create_function A pointer to a function that will return a
    //! constructed instance of the class.
    //! @returns A bool indicating whether or not the class given by p_type was
    //! already registered.
    static bool Register(const std::string& p_type,
                         const Create_Function& p_create_function);

    //! @brief Retrieves a list of all of the models that have been compiled
    //! and whether or not they are enabled. TODO: Make the code match this
    //! brief.
    //! @returns An unordered_map, indexed by the name of the model, containing
    //! boolean values indicating as to whether that model is enabled by
    //! default. TODO: Change this
    //! @note This is a function wrapper around a static object using the
    //! "Construct members on first use idiom". This is needed to guarentee that
    //! the unordered_map is initalised whilst the factory contents are
    //! registering themselves. This is a work around for the well known static
    //! initialisation order fiasco.
    //! @see https://isocpp.org/wiki/faq/ctors#static-init-order
    //! @see
    //! https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use-members
    static std::unordered_map<std::string, Create_Function>& Get_All_Models();

private:
    //! @brief This has been deleted to ensure the constructor and the copy
    //! constructor cannot be called as this is just a utility class containing
    //! nothing but static functions.
    Model_Factory(const Model_Factory&) = delete;
};
} // namespace Internal
} // namespace ELMO2

#endif
